// This file is auto-generated by @hey-api/openapi-ts

export type AssignTaskCommand = {
  assigned_to_id: string
  task_id: string
  title: string
  description: string
  requires_approval: boolean
}

export type AvailableTaskPublic = {
  title: string
  description?: string | null
  requires_approval?: boolean
  approved?: boolean
  department_xp?: number
  skill_xp?: number
  company_xp?: number
  person_xp?: number
  is_active?: boolean
  id: string
}

export type AvailableTasksPublic = {
  data: Array<AvailableTaskPublic>
  count: number
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type CancelTaskCommand = {
  aggregate_id: string
  reason: string
}

export type Command = {
  aggregate_id: string
}

export type CompanyRead = {
  id?: string
  name: string
  current_xp?: number
  level?: number
}

export type EmployeeTask = {
  task_id: string | null
  status: string
  created_at?: string
  title?: string | null
  description?: string | null
  version?: number
  completed_at: string | null
  reason?: string | null
  requires_approval?: boolean
  submitted_at: string | null
  id?: string
  assigned_to_id: string
  approved_by_id: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type RejectTaskCommand = {
  aggregate_id: string
  reason: string
  approved_by_id: string
}

export type SubmitTaskCommand = {
  aggregate_id: string
}

export type TaskEvent = {
  id?: string
  aggregate_id: string
  timestamp: string
  version: number
  event_type: string
  assigned_to_id: string | null
  task_id: string | null
  reason?: string | null
  approved_by_id: string | null
}

export type TaskEventDomain = {
  aggregate_id: string
  timestamp: string
  version: number
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  current_xp?: number
  password: string
  company_id: string
  department_id: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  current_xp?: number
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  current_xp?: number
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type CompaniesReadCompanyResponse = CompanyRead

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type TasksReadTasksData = {
  limit?: number
  onlyActive?: boolean
  skip?: number
}

export type TasksReadTasksResponse = AvailableTasksPublic

export type TasksAssignTaskData = {
  requestBody: AssignTaskCommand
}

export type TasksAssignTaskResponse = string

export type TasksSubmitTaskData = {
  requestBody: SubmitTaskCommand
}

export type TasksSubmitTaskResponse = TaskEventDomain

export type TasksSubmitTask1Data = {
  requestBody: Command
}

export type TasksSubmitTask1Response = TaskEventDomain

export type TasksSubmitTask2Data = {
  requestBody: RejectTaskCommand
}

export type TasksSubmitTask2Response = TaskEventDomain

export type TasksCancelTaskData = {
  requestBody: CancelTaskCommand
}

export type TasksCancelTaskResponse = TaskEventDomain

export type TasksGetEmployeeTasksData = {
  id: string
}

export type TasksGetEmployeeTasksResponse = Array<EmployeeTask>

export type TasksGetTasksEventData = {
  id: string
}

export type TasksGetTasksEventResponse = Array<TaskEvent>

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
