"""Adjusted models

Revision ID: 085cbf2a8401
Revises: 04595182e73b
Create Date: 2025-01-26 11:03:40.244112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '085cbf2a8401'
down_revision = '04595182e73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_xp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_xp', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
