"""Employee Skill and Global Skill added

Revision ID: 18e2db316f95
Revises: b854c6aa159a
Create Date: 2025-01-27 20:45:06.113885

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '18e2db316f95'
down_revision = 'b854c6aa159a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalskill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employeeskill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['globalskill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('skill')
    op.drop_constraint('availabletask_skill_id_fkey', 'availabletask', type_='foreignkey')
    op.create_foreign_key(None, 'availabletask', 'globalskill', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'employee_levels', ['employee_level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'availabletask', type_='foreignkey')
    op.create_foreign_key('availabletask_skill_id_fkey', 'availabletask', 'skill', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_table('skill',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='skill_department_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='skill_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='skill_pkey')
    )
    op.drop_table('employeeskill')
    op.drop_table('globalskill')
    # ### end Alembic commands ###
