"""Relationship plays

Revision ID: 1f355c2483a0
Revises: 4e0004b6ac83
Create Date: 2025-01-26 11:21:44.245681

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1f355c2483a0'
down_revision = '4e0004b6ac83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
