"""Adjusted relationship

Revision ID: 340e7ce56ddf
Revises: 1a156fbcafff
Create Date: 2025-01-23 11:24:57.235408

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '340e7ce56ddf'
down_revision = '1a156fbcafff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
