"""Adjusted defaults

Revision ID: 43a356f3fc54
Revises: 340e7ce56ddf
Create Date: 2025-01-23 12:57:42.205023

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '43a356f3fc54'
down_revision = '340e7ce56ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('availabletask', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employeetask', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employeetask', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employeetask', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('taskevent', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskevent', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employeetask', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employeetask', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employeetask', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('availabletask', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
