"""Adjusted relationship

Revision ID: 4e0004b6ac83
Revises: 085cbf2a8401
Create Date: 2025-01-26 11:08:50.413311

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e0004b6ac83'
down_revision = '085cbf2a8401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'employee_levels', ['employee_id'])
    op.drop_constraint('employee_levels_employee_id_fkey', 'employee_levels', type_='foreignkey')
    op.create_foreign_key(None, 'employee_levels', 'user', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_levels', type_='foreignkey')
    op.create_foreign_key('employee_levels_employee_id_fkey', 'employee_levels', 'user', ['employee_id'], ['id'])
    op.drop_constraint(None, 'employee_levels', type_='unique')
    # ### end Alembic commands ###
