"""Adjusted aggregate

Revision ID: 4e8e517f4717
Revises: 43a356f3fc54
Create Date: 2025-01-23 13:55:01.652006

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e8e517f4717'
down_revision = '43a356f3fc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskevent', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('taskevent', sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.alter_column('taskevent', 'assigned_to_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('taskevent', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskevent', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('taskevent', 'assigned_to_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('taskevent', 'event_type')
    op.drop_column('taskevent', 'id')
    # ### end Alembic commands ###
