"""Skills added

Revision ID: 963cbedf8aad
Revises: e30ca1fb63cc
Create Date: 2025-01-18 18:28:28.492103

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '963cbedf8aad'
down_revision = 'e30ca1fb63cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employeetask', sa.Column('skill_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'employeetask', 'skill', ['skill_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('current_xp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_xp')
    op.drop_constraint(None, 'employeetask', type_='foreignkey')
    op.drop_column('employeetask', 'skill_id')
    op.drop_table('skill')
    # ### end Alembic commands ###
