"""Relationship adjustment

Revision ID: c3e04007b6b3
Revises: 1f355c2483a0
Create Date: 2025-01-26 11:43:18.796564

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c3e04007b6b3'
down_revision = '1f355c2483a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_levels', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user', 'employee_level_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'employee_level_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('employee_levels', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
