"""Adjusted tasks

Revision ID: e6d087adb6cf
Revises: 9310f08b039e
Create Date: 2025-01-20 13:59:14.346012

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e6d087adb6cf'
down_revision = '9310f08b039e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employeetask', sa.Column('company_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'employeetask', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employeetask', type_='foreignkey')
    op.drop_column('employeetask', 'company_id')
    # ### end Alembic commands ###
